// 세계 주요 산맥/산계 라벨. 좌표는 산맥 전체의 대략적인 중심 표시점이다.

export const WORLD_MOUNTAIN_RANGE_LABELS = [
  { name: "히말라야 산맥", lat: 28.0, lon: 84.0, minZoom: 4, maxZoom: 8, type: "mountainRange" },
  { name: "카라코람 산맥", lat: 35.7, lon: 76.5, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "힌두쿠시 산맥", lat: 35.0, lon: 70.0, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "티베트 고원", lat: 32.0, lon: 88.0, minZoom: 4, maxZoom: 8, type: "mountainRange" },
  { name: "쿤룬 산맥", lat: 36.0, lon: 84.0, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "톈산 산맥", lat: 42.0, lon: 80.0, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "알타이 산맥", lat: 49.0, lon: 88.0, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "자그로스 산맥", lat: 31.5, lon: 51.0, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "엘부르즈 산맥", lat: 36.2, lon: 52.0, minZoom: 6, maxZoom: 9, type: "mountainRange" },
  { name: "코카서스 산맥", lat: 43.3, lon: 44.5, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "우랄 산맥", lat: 60.0, lon: 60.0, minZoom: 4, maxZoom: 8, type: "mountainRange" },
  { name: "알프스 산맥", lat: 46.6, lon: 9.0, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "피레네 산맥", lat: 42.6, lon: 0.5, minZoom: 6, maxZoom: 9, type: "mountainRange" },
  { name: "아펜니노 산맥", lat: 42.0, lon: 13.0, minZoom: 6, maxZoom: 9, type: "mountainRange" },
  { name: "카르파티아 산맥", lat: 47.0, lon: 24.0, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "스칸디나비아 산맥", lat: 64.0, lon: 14.0, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "아틀라스 산맥", lat: 31.0, lon: -6.0, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "에티오피아 고원", lat: 9.5, lon: 39.5, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "드라켄즈버그 산맥", lat: -29.0, lon: 29.0, minZoom: 6, maxZoom: 9, type: "mountainRange" },
  { name: "그레이트디바이딩 산맥", lat: -27.0, lon: 152.0, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "서던알프스", lat: -43.5, lon: 170.5, minZoom: 6, maxZoom: 9, type: "mountainRange" },
  { name: "로키 산맥", lat: 45.0, lon: -113.0, minZoom: 4, maxZoom: 8, type: "mountainRange" },
  { name: "캐스케이드 산맥", lat: 45.0, lon: -121.5, minZoom: 6, maxZoom: 9, type: "mountainRange" },
  { name: "시에라네바다 산맥", lat: 37.5, lon: -119.5, minZoom: 6, maxZoom: 9, type: "mountainRange" },
  { name: "애팔래치아 산맥", lat: 38.0, lon: -80.0, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "알래스카 산맥", lat: 63.0, lon: -150.0, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "안데스 산맥", lat: -20.0, lon: -68.0, minZoom: 4, maxZoom: 8, type: "mountainRange" },
  { name: "중앙아메리카 산맥", lat: 14.5, lon: -89.0, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "시호테알린 산맥", lat: 46.0, lon: 136.0, minZoom: 6, maxZoom: 9, type: "mountainRange" },
  { name: "대흥안령 산맥", lat: 49.0, lon: 122.0, minZoom: 5, maxZoom: 9, type: "mountainRange" },
  { name: "일본 알프스", lat: 36.2, lon: 137.7, minZoom: 6, maxZoom: 9, type: "mountainRange" },
  { name: "백두대간", lat: 37.5, lon: 128.5, minZoom: 6, maxZoom: 10, type: "mountainRange" },
  { name: "태백산맥", lat: 37.4, lon: 128.7, minZoom: 7, maxZoom: 10, type: "mountainRange" },
  { name: "소백산맥", lat: 36.6, lon: 128.0, minZoom: 7, maxZoom: 10, type: "mountainRange" },
  { name: "광주산맥", lat: 37.9, lon: 127.9, minZoom: 7, maxZoom: 11, type: "mountainRange" },
  { name: "차령산맥", lat: 36.7, lon: 127.3, minZoom: 7, maxZoom: 11, type: "mountainRange" },
  { name: "노령산맥", lat: 35.6, lon: 127.1, minZoom: 7, maxZoom: 11, type: "mountainRange" },
  { name: "마천령산맥", lat: 41.3, lon: 129.0, minZoom: 7, maxZoom: 11, type: "mountainRange" },
  { name: "함경산맥", lat: 40.6, lon: 128.5, minZoom: 6, maxZoom: 11, type: "mountainRange" },
  { name: "부전령산맥", lat: 40.3, lon: 127.3, minZoom: 7, maxZoom: 11, type: "mountainRange" },
  { name: "낭림산맥", lat: 40.2, lon: 126.6, minZoom: 6, maxZoom: 11, type: "mountainRange" },
  { name: "강남산맥", lat: 40.5, lon: 125.7, minZoom: 7, maxZoom: 11, type: "mountainRange" },
  { name: "적유령산맥", lat: 40.1, lon: 126.1, minZoom: 7, maxZoom: 11, type: "mountainRange" },
  { name: "묘향산맥", lat: 39.9, lon: 126.3, minZoom: 7, maxZoom: 11, type: "mountainRange" },
  { name: "언진산맥", lat: 38.9, lon: 126.4, minZoom: 7, maxZoom: 11, type: "mountainRange" },
  { name: "멸악산맥", lat: 38.4, lon: 126.1, minZoom: 7, maxZoom: 11, type: "mountainRange" },
  { name: "마식령산맥", lat: 38.6, lon: 126.6, minZoom: 7, maxZoom: 11, type: "mountainRange" },
];
